### ISSUE TITLE
[Item Display] Display immediately breaks

### ISSUE THREAD

**Issue by dentatar** [legopitstop/Datapacks#5]
## Name of the datapack
Item Display

## Describe the bug
Display immediately breaks after creation

## Steps To Reproduce
1. Place a valid beacon base block 
2. Drop any item on it
3. Drop item frame on it
4. Hear an item frame sound followed by a red text

## Expected behavior
A working item display.

## Desktop
 - Minecraft Version: 1.19.4
 - Datapack Version 1.3.0
 - OS: Windows 10

## Additional context
I really like this item frame dropping interaction and would love to see it fixed. Thank you!

**Comment by legopitstop** [comment]
Fixed in v1.4.0
